### PR TITLE
Hei tracker

### PR DESCRIPTION
**Pull request by KorirC**
`[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
List any dependencies that are required for this change.]`

https://link.to/ticket

**Type of change**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

What tests did you run to verify your changes? Provide instructions so we can reproduce. Please also list any relevant
details for your test configuration

##### Checklist:

- [x] This review follows the [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by MugahJ — CHANGES_REQUESTED** [review]
@KorirC  Your code seems to be mixed up between hei_tracker and hiv_risk_screening tool. Please review and if you are working on the two forms, separate and commit in two branches. If not correct. Kindly but urgently finalize on this by 4 pm today. @mugaya Review once submitted back

**Comment by MugahJ** [comment]
@KorirC Also, do your PRs to upgrade, not main. Thanks

**Comment by KorirC** [comment]
> @KorirC Your code seems to be mixed up between hei_tracker and hiv_risk_screening tool. Please review and if you are working on the two forms, separate and commit in two branches. If not correct. Kindly but urgently finalize on this by 4 pm today. @mugaya Review once submitted back

There was a conflict where the upgrade had the hiv_risk_screening tool while on my branch didn't and i did resolve it by accepting the new changes merged to the main

**Comment by KorirC** [comment]
> @KorirC Also, do your PRs to upgrade, not main. Thanks

Alright, will work on that

**Pull request merged**
